#!/bin/bash
# This is a convenience script for rendering .dot files generated by running a
# Qwerty program with the environment variable QWERTY_DEBUG=1. You will need
# graphviz installed to use it.
# The usage is:
#     ./render.sh something.dot
# which will produce something.png you can open in an image viewer.

exec dot -Tpng <"$1" >"${1%.dot}.png"
