#!/usr/bin/env python3

"""
Generates ``synth-arith.mlir``, a FileCheck test that tests an 4-bit adder on
all possible inputs.
"""

import os
import sys

OUT_PATH = os.path.join(os.path.dirname(__file__), 'synth-arith.mlir')

N_BITS = 4

PROLOGUE = f"""// RUN: qwerty-opt -convert-ccirc-to-func-arith -canonicalize -convert-vector-to-llvm -convert-func-to-llvm -convert-arith-to-llvm %s | mlir-runner -e test -entry-point-result=void --shared-libs=%mlir_c_runner_utils | FileCheck --match-full-lines %s

// This file is generated by gen-arith-tests.py. Do not edit this file
// manually.

ccirc.circuit @add(%a: !ccirc<wire[{N_BITS}]>, %b: !ccirc<wire[{N_BITS}]>) irrev {{
    %0 = ccirc.add(%a, %b) : (!ccirc<wire[{N_BITS}]>, !ccirc<wire[{N_BITS}]>) -> !ccirc<wire[{N_BITS}]>
    ccirc.return %0 : !ccirc<wire[{N_BITS}]>
}}

func.func @check_add(%a: i{N_BITS}, %b: i{N_BITS}) -> () {{
    %func = ccirc.func_ptr @add : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    %res = func.call_indirect %func(%a, %b) : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    vector.print %res : i{N_BITS}
    return
}}

func.func @test() {{
"""

EPILOGUE = """
    return
}
"""

def format_constant(c):
    return f"    %c{c} = arith.constant {c} : i{N_BITS}\n"

def format_test(c1, c2):
    sum = (c1 + c2) & ((1 << N_BITS) - 1)
    res = sum if sum < (1 << (N_BITS - 1)) else sum | (-1 << N_BITS)
    return f"""
    // 0x{c1:02x} + 0x{c2:02x} = 0x{sum:02x}
    // CHECK: {res}
    func.call @check_add(%c{c1}, %c{c2}) : (i{N_BITS}, i{N_BITS}) -> ()
"""

def main():
    with open(OUT_PATH, 'w') as fp:
        fp.write(PROLOGUE)

        for c in range(1 << N_BITS):
            fp.write(format_constant(c))

        for c1 in range(1 << N_BITS):
            for c2 in range(1 << N_BITS):
                fp.write(format_test(c1, c2))

        fp.write(EPILOGUE)

    return 0

if __name__ == '__main__':
    sys.exit(main())
