#!/usr/bin/env python3

"""
Generates ``synth-arith.mlir``, a FileCheck test that tests an 4-bit adder, an
4-bit subtractor, and 4-bit modular doubling, addition, and multiplication on
all possible inputs.
"""

import os
import sys

OUT_PATH = os.path.join(os.path.dirname(__file__), 'synth-arith.mlir')

N_BITS = 4
# Moduli that fit in N_BITS bits. A modulus of 1 reduces everything to zero, so
# there is not much point in testing it
MODULI = range(2, 1 << N_BITS)

PROLOGUE = f"""// RUN: qwerty-opt -convert-ccirc-to-func-arith -canonicalize -convert-vector-to-llvm -convert-func-to-llvm -convert-arith-to-llvm %s | mlir-runner -e test -entry-point-result=void --shared-libs=%mlir_c_runner_utils | FileCheck --match-full-lines %s

// This file is generated by gen-arith-tests.py. Do not edit this file
// manually.

ccirc.circuit @add(%a: !ccirc<wire[{N_BITS}]>, %b: !ccirc<wire[{N_BITS}]>) irrev {{
    %0 = ccirc.add(%a, %b) : (!ccirc<wire[{N_BITS}]>, !ccirc<wire[{N_BITS}]>) -> !ccirc<wire[{N_BITS}]>
    ccirc.return %0 : !ccirc<wire[{N_BITS}]>
}}

ccirc.circuit @sub(%a: !ccirc<wire[{N_BITS}]>, %b: !ccirc<wire[{N_BITS}]>) irrev {{
    %0 = ccirc.sub(%a, %b) : (!ccirc<wire[{N_BITS}]>, !ccirc<wire[{N_BITS}]>) -> !ccirc<wire[{N_BITS}]>
    ccirc.return %0 : !ccirc<wire[{N_BITS}]>
}}

func.func @check_add(%a: i{N_BITS}, %b: i{N_BITS}) -> () {{
    %func = ccirc.func_ptr @add : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    %res = func.call_indirect %func(%a, %b) : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    vector.print %res : i{N_BITS}
    return
}}

func.func @check_sub(%a: i{N_BITS}, %b: i{N_BITS}) -> () {{
    %func = ccirc.func_ptr @sub : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    %res = func.call_indirect %func(%a, %b) : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    vector.print %res : i{N_BITS}
    return
}}
"""

TEST_PROLOGUE = """
func.func @test() {
"""

EPILOGUE = """
    return
}
"""

def format_constant(c):
    return f"    %c{c} = arith.constant {c} : i{N_BITS}\n"

def to_signed(val):
    val &= (1 << N_BITS) - 1
    return val if val < (1 << (N_BITS - 1)) else val | (-1 << N_BITS)

def format_add_test(c1, c2):
    sum = (c1 + c2) & ((1 << N_BITS) - 1)
    res = to_signed(sum)
    return f"""
    // CHECK: {res}
    func.call @check_add(%c{c1}, %c{c2}) : (i{N_BITS}, i{N_BITS}) -> () // 0x{c1:02x} + 0x{c2:02x} = 0x{sum:02x}
"""

def format_sub_test(c1, c2):
    diff = (c1 - c2) & ((1 << N_BITS) - 1)
    res = to_signed(diff)
    return f"""
    // CHECK: {res}
    func.call @check_sub(%c{c1}, %c{c2}) : (i{N_BITS}, i{N_BITS}) -> () // 0x{c1:02x} - 0x{c2:02x} = 0x{diff:02x}
"""

# The modulus is an attribute rather than an operand, so every modulus tested
# needs a circuit of its own
def format_double_mod_circuit(modN):
    return f"""
ccirc.circuit @double_mod_{modN}(%a: !ccirc<wire[{N_BITS}]>) irrev {{
    %0 = ccirc.double_mod {modN} %a : (!ccirc<wire[{N_BITS}]>) -> !ccirc<wire[{N_BITS}]>
    ccirc.return %0 : !ccirc<wire[{N_BITS}]>
}}

func.func @check_double_mod_{modN}(%a: i{N_BITS}) -> () {{
    %func = ccirc.func_ptr @double_mod_{modN} : (i{N_BITS}) -> (i{N_BITS})
    %res = func.call_indirect %func(%a) : (i{N_BITS}) -> (i{N_BITS})
    vector.print %res : i{N_BITS}
    return
}}
"""

def format_double_mod_test(modN, c):
    doubled = (2 * c) % modN
    res = to_signed(doubled)
    return f"""
    // CHECK: {res}
    func.call @check_double_mod_{modN}(%c{c}) : (i{N_BITS}) -> () // 2*0x{c:02x} % {modN} = 0x{doubled:02x}
"""

def format_add_mod_circuit(modN):
    return f"""
ccirc.circuit @add_mod_{modN}(%a: !ccirc<wire[{N_BITS}]>, %b: !ccirc<wire[{N_BITS}]>) irrev {{
    %0 = ccirc.add_mod {modN} %a, %b : (!ccirc<wire[{N_BITS}]>, !ccirc<wire[{N_BITS}]>) -> !ccirc<wire[{N_BITS}]>
    ccirc.return %0 : !ccirc<wire[{N_BITS}]>
}}

func.func @check_add_mod_{modN}(%a: i{N_BITS}, %b: i{N_BITS}) -> () {{
    %func = ccirc.func_ptr @add_mod_{modN} : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    %res = func.call_indirect %func(%a, %b) : (i{N_BITS}, i{N_BITS}) -> (i{N_BITS})
    vector.print %res : i{N_BITS}
    return
}}
"""

def format_add_mod_test(modN, c1, c2):
    summed = (c1 + c2) % modN
    res = to_signed(summed)
    return f"""
    // CHECK: {res}
    func.call @check_add_mod_{modN}(%c{c1}, %c{c2}) : (i{N_BITS}, i{N_BITS}) -> () // (0x{c1:02x} + 0x{c2:02x}) % {modN} = 0x{summed:02x}
"""

# ccirc.modmul multiplies by x^(2^j) % N, but DecomposeModMul does that
# squaring classically before synthesis ever runs. Sweeping every x at j=0
# therefore already covers every multiplier the synthesized circuit can see, so
# j > 0 only needs enough coverage to catch the squaring itself drifting. One
# modulus swept exhaustively does that without tripling the size of this file.
SQUARING_MODULUS = (1 << N_BITS) - 1
SQUARING_EXPONENTS = range(1, 4)

def effective_multiplier(x, j, modN):
    x_2j_modN = x % modN
    for _ in range(j):
        x_2j_modN = (x_2j_modN * x_2j_modN) % modN
    return x_2j_modN

def format_modmul_circuit(x, j, modN):
    return f"""
ccirc.circuit @modmul_{x}_{j}_{modN}(%y: !ccirc<wire[{N_BITS}]>) irrev {{
    %0 = ccirc.modmul {x} {j} {modN} %y : (!ccirc<wire[{N_BITS}]>) -> !ccirc<wire[{N_BITS}]>
    ccirc.return %0 : !ccirc<wire[{N_BITS}]>
}}

func.func @check_modmul_{x}_{j}_{modN}(%y: i{N_BITS}) -> () {{
    %func = ccirc.func_ptr @modmul_{x}_{j}_{modN} : (i{N_BITS}) -> (i{N_BITS})
    %res = func.call_indirect %func(%y) : (i{N_BITS}) -> (i{N_BITS})
    vector.print %res : i{N_BITS}
    return
}}
"""

def format_modmul_test(x, j, modN, c):
    product = (effective_multiplier(x, j, modN) * c) % modN
    res = to_signed(product)
    return f"""
    // CHECK: {res}
    func.call @check_modmul_{x}_{j}_{modN}(%c{c}) : (i{N_BITS}) -> () // (0x{x:02x}^(2^{j}) % {modN})*0x{c:02x} % {modN} = 0x{product:02x}
"""

def main():
    with open(OUT_PATH, 'w') as fp:
        fp.write(PROLOGUE)

        for modN in MODULI:
            fp.write(format_double_mod_circuit(modN))
            fp.write(format_add_mod_circuit(modN))
            for x in range(modN):
                fp.write(format_modmul_circuit(x, 0, modN))
                if modN == SQUARING_MODULUS:
                    for j in SQUARING_EXPONENTS:
                        fp.write(format_modmul_circuit(x, j, modN))

        fp.write(TEST_PROLOGUE)

        for c in range(1 << N_BITS):
            fp.write(format_constant(c))

        for c1 in range(1 << N_BITS):
            for c2 in range(1 << N_BITS):
                fp.write(format_add_test(c1, c2))

        for c1 in range(1 << N_BITS):
            for c2 in range(1 << N_BITS):
                fp.write(format_sub_test(c1, c2))

        # The modular routines assume their inputs are already reduced mod N
        for modN in MODULI:
            for c in range(modN):
                fp.write(format_double_mod_test(modN, c))

        for modN in MODULI:
            for c1 in range(modN):
                for c2 in range(modN):
                    fp.write(format_add_mod_test(modN, c1, c2))

        for modN in MODULI:
            for x in range(modN):
                for c in range(modN):
                    fp.write(format_modmul_test(x, 0, modN, c))

        # Spot check that the repeated squaring in DecomposeModMul lines up
        for x in range(SQUARING_MODULUS):
            for j in SQUARING_EXPONENTS:
                for c in range(SQUARING_MODULUS):
                    fp.write(format_modmul_test(x, j, SQUARING_MODULUS, c))

        fp.write(EPILOGUE)

    return 0

if __name__ == '__main__':
    sys.exit(main())
